### ISSUE TITLE
generate random cron and language expression

### ISSUE THREAD

**Issue by arvindpunk** [osdc/crontab.training#2]
On page load,
we need to generate the following
1. `1 * * * *` - the cron value
2. The human readable language equivalent (https://github.com/bradymholt/cRonstrue)

And display them side-by-side.

Scope your PR to only this, no other additional logic/styling/css.

**Comment by glokta1** [comment]
Generating a random cron value seems tedious given the number of ways each placeholder can be formatted. 
For e.g.
![CleanShot 2023-11-05 at 15 39 29@2x](https://github.com/osdc/crontab.training/assets/71697384/1538e8dc-ef19-463d-a8d2-16019d693dc7)

**Comment by arvindpunk** [comment]
@glokta1 crontab.guru has a random button itself (top right of the input box)

**Comment by arvindpunk** [comment]
I see, seems like they have a list of hard-coded values
```js
o = [
  '5 0 * 8 *',
  '15 14 1 * *',
  '0 22 * * 1-5',
  '23 0-20/2 * * *',
  '5 4 * * sun',
  '0 0,12 1 */2 *',
  '0 4 8-14 * *',
  '0 0 1,15 * 3',
  '@weekly'
]```

Let's just start with a basic generator that generates simple ones then?
For each 5 places, 
- 70% chance of `*`
- 30% chance of a random (allowed) value
